### ISSUE TITLE
tf-grid agent

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtecharchive/grid3_client_go#128]
create an agent for tf-grid cli

the idea is exposing the functionality of tfgrid cli tool using a subcommand `tf-grid agent` that starts a new server listening on a redis queue that receives commands (well defined ones) with arguments 

- check [zbus](https://github.com/threefoldtech/zbus) to register commands and run a redis server 
- check attachments for expected commands 
[cmd_requirements.md](https://github.com/threefoldtech/grid3_client_go/files/10998242/cmd_requirements.md)

**Comment by AbdelrahmanElawady** [comment]
- [ ] add tfgrid interface 
- [ ] add tfgrid implementation 
- [ ] add login action
- [ ] add server start cmd

**Comment by xmonader** [comment]
Mario is continuing on this one
