### ISSUE TITLE
the manager should persist state

### ISSUE THREAD

**Issue by mariobassem** [threefoldtecharchive/grid3_client_go#27]
a user should be able to choose whether or not they want to persist state. Also they should decide where and how they want to store it.

**Comment by xmonader** [comment]
the goal of the project is indeed to be a reusable library for terraform, however, terraform provides it's own state / remote state solutions which will only work in case of terraform only, but if we want to expand the project to be used ultimately in things like terraform, pulumi, and whatnot, and if we want to be also compatible with what shows up in the weblets playground we need to start thinking about a state component, that can support e.g
- local file system
- keyvalue module of tfchain
- s3 backend
